---
framework: mocha
blacklist:
  - "test/unit/adapters/http-3.js##oh wow##should allow passing NEW JSON"
  - "test/unit/adapters/http-3.js##oh wow##should redirect"
docker:
  auth:
    password: $DOCKERHUB_PASSWORD
    username: mydockerhub-user
  image: "lambdatest/<language>:<version TAG>"
modifiers:
  - type: mocha
    config: cnf/mocha.ini
  - type: jest
    cli: "--forbid-pending --no-bail"
postmerge:
  pattern:
    - "test/unit/adapters/**/*.js"
    - "test/unit/adapters/http-2.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
premerge:
  - "test/unit/adapters/**/*.js"
  - "test/unit/adapters/http-2.js"
stability:
  consecutive_runs: 5
prerun:
  - date
  - who am i
postrun:
  - node --version
  - ifconfig
version: 2.0
